# Generated by Django 4.0.6 on 2022-07-10 10:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/product_photos', verbose_name='Foto')),
                ('description', models.CharField(max_length=1000, verbose_name='Descrição')),
                ('aquisition_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de aquisição')),
                ('aquisition_data', models.DateField(verbose_name='Data de aquisição')),
                ('sell_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Preço de venda')),
                ('credit_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Preço a prazo')),
                ('genre', models.CharField(choices=[('MENINO', 'Menino'), ('MENINA', 'Menina')], max_length=6, verbose_name='Gênero')),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=46, verbose_name='Tamanho')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade em estoque')),
            ],
            options={
                'verbose_name': 'Produto',
                'ordering': ('-aquisition_data',),
            },
        ),
    ]
