# Generated by Django 4.0.6 on 2022-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/product_photos')),
                ('description', models.CharField(max_length=1000)),
                ('aquisition_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aquisition_data', models.DateField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.CharField(choices=[('MENINO', 'Menino'), ('MENINA', 'Menina')], max_length=6)),
                ('size', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=2)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ('-aquisition_data',),
            },
        ),
    ]
