# Generated by Django 4.0.6 on 2022-07-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aquisition_data',
            field=models.DateField(verbose_name='Data de aquisição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='aquisition_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de aquisição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('MENINO', 'Menino'), ('MENINA', 'Menina')], max_length=6, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade em estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de venda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=2, verbose_name='Tamanho'),
        ),
    ]
