# Generated by Django 4.0.6 on 2022-07-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_product_aquisition_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-aquisition_data',), 'verbose_name': 'Produto'},
        ),
    ]
