# Generated by Django 4.0.6 on 2022-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Em estoque:'),
        ),
    ]
