# Generated by Django 4.0.6 on 2022-07-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_remove_product_quantity_alter_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product_photos', verbose_name='Foto'),
        ),
    ]
