# Generated by Django 4.0.6 on 2022-07-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.CharField(max_length=3000, verbose_name='URL da imagem'),
        ),
    ]
